name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream and Fetch Changes
        run: |
          git remote add upstream https://github.com/aem-showcase/frescopa.git
          git fetch upstream
          git checkout main
          git merge --no-commit --no-ff upstream/main || echo "No changes to merge"

      - name: Restore fstab.yaml (Preserve from Fork)
        run: |
          cp fstab.yaml ../fstab_backup.yaml || echo "No existing fstab.yaml to back up"
          git checkout --ours fstab.yaml || echo "fstab.yaml not in conflict"
          mv ../fstab_backup.yaml fstab.yaml || echo "No backup needed"
          git add fstab.yaml

      - name: Authenticate with GitHub and Push Changes
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git commit -m "Sync from upstream, preserving fstab.yaml" || echo "No changes to commit"
          git push origin main
